### ISSUE TITLE
Turn on/off not working

### ISSUE THREAD

**Issue by jtbarber** [bklavet/Echo-skill-to-control-Directv#46]
I have a genie setup and everything is working great except I can't turn the DTV box on or off. I try "power" and that doesn't work, I just get a beep on the box. I tried "turn on" and that doesn't work. I have noticed that "turn on" and "turn off" are in the custom slot values but I don't see it in the index. How can I add this?

**Comment by bklavet** [comment]
If I remember right, I removed it because once the receiver turned off, it shuts down its lan connection so the power on command wouldn't work.  I know this Doesn't make sense to have the commands in she.f protocol when the hardware Doesn't keep it working when powered down. But that was my experience,

**Comment by bklavet** [comment]
well i did some checking and i did leave the "power" in the custom slot
			case "power":
                        path = '/remote/processKey?key=power&hold=keyPress';
                break;

if you wanted to see if the "turn on/ turn off" works for you.  you can alter your index to look like this:
case "power":
case "turn on":
case "turn off":
                        path = '/remote/processKey?key=power&hold=keyPress';
                break;
