### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by wwwgizy** [bklavet/Echo-skill-to-control-Directv#50]
Error: There was a problem with your request: Unknown slot type 'Control_List' for slot 'Control'

**Comment by bklavet** [comment]
the problem is going to be on the Interaction Model tab in the Amazon Developer Console.  when you get "Error: There was a problem with your request: Unknown slot type 'Control_List' for slot 'Control' this means that the Control_List entered in the custom slot Type does not match the Control_List in the schema.  you may have a space somewhere that you got with the pasting, but that is where your problem lies.  Thanks﻿

**Comment by wwwgizy** [comment]
Can you help me with team viewer?

**Comment by vmweaver** [comment]
@wwwgizy I know this is an old issue, but did you get it resolved?

**Comment by vmweaver** [comment]
Closing issue
