### ISSUE TITLE
mini client works perfectly. main dvr doesn't work after alexa command.

### ISSUE THREAD

**Issue by jamesds1** [bklavet/Echo-skill-to-control-Directv#52]
The mini client works perfectly with all commands. My main HR44 will not work after Alexa command. Alexa says "okay" however no action from dvr. My dvr is out on DMZ.

**Comment by bklavet** [comment]
Hello James, good to read you have had success on the mini, are you able to control the hr44 from outside your home network?

If you enter this using the main genie's ip, do you see both the minis and the main?
http://[lanIP]:8080/info/getLocations
 
Usually getting the mini's to work are more difficult for some because they have to build the mac address into the skill, with no mac entered the main should be controllable by default, what version of the skill are you using for the hr44?

**Comment by jamesds1** [comment]
I cannot connect to dvr/clients via lan. Our HR-200 is rotating its IP address with its assigned and the respective clients. When it reassigns itself, I still have control of the client. I even changed the the client location via the index file and reconfigured the custom slot skill and Lambda page and it worked with other clients.  I suspect this is a either a router or dvr problem. Directv will be here Wednesday morning to upgrade to the HS17, Genie 2. It may present other problems as it's a totally wireless network, that is, the Genie 2 is installed anywhere with a solid signal and is connected to each respective flat screen via wireless clients. The WVB is part of the Genie unit itself.

I will revisit this when later this week. Thank you for your prompt replies and help.

Have a great week!!!!

James

**Comment by bklavet** [comment]
Hello James, I think you will have better luck with the genie, when you get it set up run the get locations command and get your Macs for all the receivers. The main genie will most likely be 0.  If you want me to take a look , let me know and I will pass my Gmail address.

Let me know if you have success though. I am cheering for you.
