### ISSUE TITLE
How to control Genie Mini?

### ISSUE THREAD

**Issue by perseids29** [bklavet/Echo-skill-to-control-Directv#8]
First of all thank you so much for all your hard work!

I can control both my Main DVR and my Genie Mini by entering the code/URL in a browser. 

My problem is that I cannot control my Genie Mini using the "Simulator Service". I am pretty sure it is because I am not referencing the client MAC in my index file. But I have no idea how or where to do that.
Do I need to build 2 separate skills, one for my Main DVR and one for my Genie Mini?

Secondly, I have not been successful in invoking the skill using my Echo :(

In the developer section or whatever I have all green checkmarks except for the "publishing" section which I do not think is necessary, correct?

I entered "Direct TV" as my invocation word.

When I say "Echo, turn on Direct TV "pause" I get no response, it just acts like she times out.

**Comment by vmweaver** [comment]
The echo handles your invocation with phrases like "alexa tell direct TV to
pause".  I believe the "turn on" invocation is reserved for other
implementations.

**Comment by perseids29** [comment]
Aha! That seemed to fix Thee issue of echo not responding. I could have sworn I used every version or combination to invoke that I could think of.

Thank you!!!

Now I just have to work on commanding the mini and I'll be ready to play!

**Comment by perseids29** [comment]
Ok... I edited my index file to include my MAC for the mini in each 'control' path. 

for example:
path= '/remote/processKey?key=right&hold=keyPress&clientAddr=XXXXXXXXXXXX

and that works! Yea!

Now I need some help to edit the "Channel" and "Network" intents... 

case "CNN":
                    path = '/tv/tune?major=202&minor=65535'

**Comment by bklavet** [comment]
I don't know if this would work or not but I would try /tv/tune?major=202&minor=65535&clientAddr=xxxxxxxxxxxx

**Comment by bklavet** [comment]
Just found this link, https://irule.desk.com/customer/portal/questions/659934-directv-genie-hr34-and-client-c31-control

If the above doesn't work try dropping the &minor=65535 and see if that does the trick.  I only have one directv box so I can't test these ideas out.

**Comment by perseids29** [comment]
Thank you once again!

I dropped the "&minor=65535" and sub'd my client MAC and it works!

I really appreciate all your help and effort!

**Comment by bklavet** [comment]
Awesome perseids29!

**Comment by mtsurumo** [comment]
@perseids29 do you have a completed code I could look at? Still can't seem to get my bedroom receivers to work with Alexa....

**Comment by bklavet** [comment]
Hello mtsurumo,  The MAC has to be added to get the path to work minis also the "&minor=65535" needs to be dropped from the channel presets.

A good start is to type this into your browser and see what you have for MAC addresses for the receivers you want to control.  This command will show you the client address (MAC) and it's assigned location name (ex "Master Bedroom").
http://[lanIP}:8080/info/getLocations
I am assuming you have the skill working, it is only controlling the main Genie though correct?

**Comment by perseids29** [comment]
I got it to turn the mini on and off and pause and stuff but never got it to change channels.
I gave up



Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mtsurumo** [comment]
Hi @bklavet I was able to pause the living room via the code you submitted in your main youtube Q&A thread leading me to believe 8080 is open. When I input my IP address, the address for the internet via my computer is different than that of the Direct TV which could be an issue? I don't have the completed code with  me at work right now but can send you a sample when I get home. I get the "remote endpoint could not be called" error when testing it via Lambda. I'm a n00b when it comes to all of this and thus far your information/video have been extremely helpful! 
@perseids29 Sorry to hear that! Will let you know if I am any more successful lol

**Comment by bklavet** [comment]
Ok mtsurumo,  So at this point the skill is not working on the living room receiver.  Is this correct?  I am thinking that you can control your receiver locally within your home network, but can not from outside it.  
Is this accurate?

I still don't have a mini receiver to test out on, but would like to keep cracking at this.
First thing we need to do though is get the skill working... in this case the living room, and then work on a duplicate skill for the mini receiver.

**Comment by mtsurumo** [comment]
Thanks bklavet! Will send you what I have once I get back. You're amazing! I would work on it today with all my downtime at work but I can't test it from here :(

**Comment by bbw4882** [comment]
Everything is working. Thanks for the efforts.  It's really cool and fun as well.  My mini genie actually seems to respond much quicker and better than my main.  I think it's because of the invocation name.  "Direct TV" being the main and simply "TV" for the genie.  Not sure if it was necessary, but I made 2 separate skills.  To clear up confusion,  on the mini genie you're correct.  For control operations  I added the MAC
 ex. &clientAddr=XXXXXXXXXXXX
so it looks like this

case "guide":
                        path = '/remote/processKey?key=guide&hold=keyPress&clientAddr=XXXXXXXXXX'
                break;

I also have all channels responding as well.  You're correct and the irule link helped me get channels responding.  I removed "&minor=6553" 
and added the MAC address for the mini here's an example
&clientAddr=XXXXXXXXXXXX
Here is what it should look like when complete

case "CNN":
					path = '/tv/tune?major=202&clientAddr=XXXXXXXXXXX';
                
				break;

All the "X" being the MACfor the mini which you can find in the settings on the DirecTv reciever

**Comment by bklavet** [comment]
bbw4882, that is outstanding!  Thanks for the information and feedback!  I also was impressed by how fast the commands are executed on the main unit, now I know the minis are responsive as well. 
Take care!

**Comment by bbw4882** [comment]
YES! Controls and Channels confirmed working.  Thanks again for the initial efforts.  One thing I'm having a minor issue with is having echo understanding NBC Sports and/orFOX Sports... Any ideas?

**Comment by bklavet** [comment]
Adding another Control_List value that is easier for alexa to understand and then updating or adding a case to the index.
Example lets say NBC never works for you, but it does, or might for someone else.  We don’t want to remove NBC altogether, but lets say when we do a Simon says command for alexa.
“Simon says NBC”
Response  is
“NVC”
You could add NVC to the Control_List and add case “NVC” to the index. Where NBC is.  Now one thing to double check is put nvc in the service simulator to see how it is going to lambda.  The case “” needs to reflect that exactly.

This way I can still say NBC and alexa may get it right or she may error to NVC, but either way, the result is the same.
Sort of like me growing up…. I for some unknown reason thought Miracle whip was merry coo whip…. And since it sounded close enough and people are kind, nobody corrected me, and it wasn’t till I was in my 20’s buying miracle whip for the first time that i had that “you got to be kidding me!” moment.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bbw4882** [comment]
Thanks!  I'll give it a shot.

One thing I'll add, I forgot to mention originally.  The MAC address needs to be entered in without the colon ( : ) and in al CAPITALIZED letters.  Hopes this helps and clears any confusion getting a genie to work.

**Comment by bklavet** [comment]
bbw4882 !
could you do me a favor and modify your index file you are using for the mini by x'ing out the app id and Mac address, wan ip and attaching it to this thread.  I would like with your permission to add it as a template for others trying to get the mini's to work.  

What do you think?

**Comment by bbw4882** [comment]
Sure thing.  Here you go.  Let me know if you've received this properly.
I've "X"ed out the iP address, amz app iD, and the MAC.  Also, in
customizing the index to suit my situation I've add a few channels (fox and
nbc sports, my locals abc, nbc, cbs, fox) and deleted one channel that I'll
never watch (AMC) so be aware it is slightly different from your original.
Only to accommodate my particular situation.  All that would need to be
done is to add the correct channel number if someone wanted to include
their locals as well.

**Comment by bklavet** [comment]
I don’t see it, could you send to bklavet@gmail.com<mailto:bklavet@gmail.com>?
Thanks  a million I really appreciate it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
